/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.trivisionsc;

public final class R {
    public static final class array {
        public static final int listNameLanguage=0x7f040000;
        public static final int listValueLanguage=0x7f040001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int audio=0x7f020000;
        public static final int clear=0x7f020001;
        public static final int dictionary=0x7f020002;
        public static final int dictmenu=0x7f020003;
        public static final int google=0x7f020004;
        public static final int info=0x7f020005;
        public static final int manage=0x7f020006;
        public static final int tri=0x7f020007;
        public static final int warning=0x7f020008;
    }
    public static final class id {
        public static final int btnAudioConvert=0x7f060001;
        public static final int btnAudioReConvert=0x7f060004;
        public static final int btnClear=0x7f060009;
        public static final int btnConvert=0x7f060006;
        public static final int btnGoogleClear=0x7f060008;
        public static final int btnReConvert=0x7f060007;
        public static final int btnSpeak=0x7f06000b;
        public static final int edtDestinationInput=0x7f060005;
        public static final int edtSourceInput=0x7f060002;
        public static final int listResult=0x7f06000d;
        public static final int radioGroup=0x7f06000e;
        public static final int spnDestinationLanguages=0x7f060003;
        public static final int spnSourceLanguages=0x7f060000;
        public static final int textView=0x7f06000c;
        public static final int word=0x7f06000a;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int google_translate=0x7f030001;
        public static final int main=0x7f030002;
        public static final int message_err=0x7f030003;
        public static final int scroll=0x7f030004;
        public static final int todolist_item=0x7f030005;
    }
    public static final class string {
        public static final int about_text=0x7f050003;
        public static final int app_name=0x7f050000;
        public static final int format_file_data=0x7f050001;
        public static final int input=0x7f050006;
        public static final int license_about=0x7f050004;
        public static final int no_database=0x7f050005;
        public static final int output=0x7f050007;
        public static final int path_file_data=0x7f050002;
    }
}
